install.packages('RCurl')
install.packages('bitops')
library(RCurl)
library(bitops)
diamondsurl = getBinaryURL('https://raw.github.com/solomonm/diamonds~data/master/BigDiamonds.Rda')
diamonds_data <- load("BigDiamonds.Rda")
summary(diamonds_data)
m1 <- lm(I(log(price)) ~ I(carat^(1/3)), data=data)
m2 <- update(m1, ~ . + carat)
m3 <- update(m2, ~ . + cut)
m4 <- update(m3, ~ . + color)
m5 <- update(m4, ~ . + clarity)
mtable(m1, m2, m3, m4, m5)
